global_frame: odom
robot_base_frame: base_footprint
update_frequency: 2.0
publish_frequency: 1.0
static_map: false
rolling_window: true
width: 4.0
height: 4.0
resolution: 0.05
transform_tolerance: 1.0

plugins:
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  max_obstacle_height: 0.2
  min_obstacle_height: 0.025
  allow_unknown: false
  track_unknown_space: true
  unknown_cost_value: -1
  lethal_cost_threshold: 100

  observation_sources: laser_scan_sensor
  
  #point_cloud_sensorA point_cloud_sensorB

  laser_scan_sensor: {
     data_type: LaserScan, 
     topic: /scan,
     obstacle_range: 3.0,
     raytrace_range: 5.0,
     marking: true, 
     clearing: true,
     inf_is_valid: true
  }

  point_cloud_sensorA: {
     sensor_frame: base_footprint,
     data_type: PointCloud2, 
     topic: obstacles_cloud, 
     expected_update_rate: 0.5, 
     marking: true, 
     clearing: true,
     min_obstacle_height: 0.04
  }

  point_cloud_sensorB: {
     sensor_frame: base_footprint,
     data_type: PointCloud2,
     topic: ground_cloud,
     expected_update_rate: 0.5,
     marking: false,
     clearing: true,
     min_obstacle_height: -1.0 # make sure the ground is not filtered
  }

