robot_radius: 0.20
inflation_radius: 0.5

observation_sources: scan

scan: {
  data_type: LaserScan,
  topic: /scan,
  marking: true,
  clearing: true,
  inf_is_valid: true,
  obstacle_range: 2.5,
  raytrace_range: 3.0,
  max_obstacle_height: 0.2,
  min_obstacle_height: 0.08
  }
  
#pointcloud: {data_type: PointCloud2, topic: /camera/depth_registered/points, marking: true, clearning: true}