robot_radius: 0.20
inflation_radius: 0.4

max_obstacle_height: 0.2
min_obstacle_height: 0.025

observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 3.0, raytrace_range: 5.0}
#scan: {data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 3.0, raytrace_range: 5.0}

#observation_sources: scan pointcloud
#scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
#pointcloud: {data_type: PointCloud2, topic: /camera/depth_registered/points, marking: true, clearning: true}
